/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DossierFile from './DossierFile';

/**
 * The Dossier model module.
 * @module model/Dossier
 * @version 1.0-SNAPSHOT
 */
class Dossier {
    /**
     * Constructs a new <code>Dossier</code>.
     * @alias module:model/Dossier
     * @param code {String} 
     * @param name {String} 
     */
    constructor(code, name) { 
        
        Dossier.initialize(this, code, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, name) { 
        obj['code'] = code;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Dossier</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Dossier} obj Optional instance to populate.
     * @return {module:model/Dossier} The populated <code>Dossier</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Dossier();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('dossierFile')) {
                obj['dossierFile'] = ApiClient.convertToType(data['dossierFile'], [DossierFile]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
Dossier.prototype['code'] = undefined;

/**
 * @member {String} name
 */
Dossier.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/DossierFile>} dossierFile
 */
Dossier.prototype['dossierFile'] = undefined;






export default Dossier;

