/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DossierFile model module.
 * @module model/DossierFile
 * @version 1.0-SNAPSHOT
 */
class DossierFile {
    /**
     * Constructs a new <code>DossierFile</code>.
     * @alias module:model/DossierFile
     * @param code {String} 
     * @param name {String} 
     */
    constructor(code, name) { 
        
        DossierFile.initialize(this, code, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, name) { 
        obj['code'] = code;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>DossierFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DossierFile} obj Optional instance to populate.
     * @return {module:model/DossierFile} The populated <code>DossierFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DossierFile();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('exists')) {
                obj['exists'] = ApiClient.convertToType(data['exists'], 'Boolean');
            }
            if (data.hasOwnProperty('readonly')) {
                obj['readonly'] = ApiClient.convertToType(data['readonly'], 'Boolean');
            }
            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
DossierFile.prototype['code'] = undefined;

/**
 * @member {String} name
 */
DossierFile.prototype['name'] = undefined;

/**
 * @member {Boolean} exists
 */
DossierFile.prototype['exists'] = undefined;

/**
 * @member {Boolean} readonly
 */
DossierFile.prototype['readonly'] = undefined;

/**
 * @member {Boolean} required
 */
DossierFile.prototype['required'] = undefined;






export default DossierFile;

