/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DossierFileView from './DossierFileView';

/**
 * The DossierView model module.
 * @module model/DossierView
 * @version 1.0.0
 */
class DossierView {
    /**
     * Constructs a new <code>DossierView</code>.
     * @alias module:model/DossierView
     * @param code {String} 
     * @param name {String} 
     */
    constructor(code, name) { 
        
        DossierView.initialize(this, code, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, name) { 
        obj['code'] = code;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>DossierView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DossierView} obj Optional instance to populate.
     * @return {module:model/DossierView} The populated <code>DossierView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DossierView();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('dossierFiles')) {
                obj['dossierFiles'] = ApiClient.convertToType(data['dossierFiles'], [DossierFileView]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
DossierView.prototype['code'] = undefined;

/**
 * @member {String} name
 */
DossierView.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/DossierFileView>} dossierFiles
 */
DossierView.prototype['dossierFiles'] = undefined;






export default DossierView;

